spring:
  application:
    name: tinyroute
  autoconfigure:
    exclude:
      - org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  data:
    redis:
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:100ms}
      timeout: ${REDIS_COMMAND_TIMEOUT:100ms}
      repositories:
        enabled: false
  jpa:
    open-in-view: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true

management:
  health:
    mail:
      enabled: false
